
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Qobolwakhe Dube
tagline: PhD Candidate at UCT
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: Lwakhe.Dube@alumni.uct.ac.za
linkedin: qobolwakhe-dube-38ab35b2
github: qobolwakhe

#Update all the sections by editing the files inside _includes folder.
